name: Test Github Action
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
    
    
jobs:
  test:
build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: file1.tex
      - name: Commit and Push new file
         run: |
              git config user.name <ychwang0331>
              git config user.email <ychwang0331@gmail.com>           
              git add .           
              git commit -m "add PDF file"           
              git push      